### ISSUE TITLE
Documentation 2 release

### ISSUE THREAD

**Issue by MylanaBulat** [liamreilly01/Sweng-Group-20#11]
Link to the document, 

- [x] Update product backlog     @MylanaBulat 
- [x] sprint planning         @WilliamWalshDowd 
- [x] sprint backlog          @WilliamWalshDowd  @MylanaBulat 
- [ ] stuff chart                 @conall47 
- [ ] Project Management with GitHub
- [ ] Implementation
- [ ] CI/CD            @liamreilly01 
- [x] Sprint Review#
- [ ] Sprint Retrospective

https://docs.google.com/document/d/16qASz7pLi_H_hAkbh8nFJPWjTO4RtaCi/edit#

**Comment by MylanaBulat** [comment]
![Image](https://user-images.githubusercontent.com/79844557/222177802-09983f84-6617-4a9e-9d80-9be4d35496c5.png)

**Comment by MylanaBulat** [comment]
@pohuigin updated the flow chart a bit

**Comment by pohuigin** [comment]
Nice job! That is very clear.
