### ISSUE TITLE
frontend

### ISSUE THREAD

**Issue by MylanaBulat** [liamreilly01/Sweng-Group-20#19]
- [x] read documentation
- [x] First implementation of front end through Django - Mahirm1
- [x] Implementation in Java script

**Comment by pohuigin** [comment]
This is a nice easy tutorial to set up a django front end https://python.plainenglish.io/set-up-a-hello-world-project-using-django-rest-framework-b6636e68a5e
And here is how to do some database stuff with it and set up an 'endpoint' for the user or a fancier front end (like reactJS or Angular to use): https://python.plainenglish.io/building-your-first-endpoint-with-the-django-rest-framework-a04bbb3a58f0
