### ISSUE TITLE
Scikit-learn prototype 1

### ISSUE THREAD

**Issue by MylanaBulat** [liamreilly01/Sweng-Group-20#7]
Work on getting yourself familiar with scikitlearn library to implement chatbot. This will give a start to implementing ML into the project .

- [ ] get familiar with the library 
- [ ] create first prototype
- [x] input to lower case 
- [x] removal of punctuation 
- [x] base form of the words 
- [x] tokenization

**Comment by brendanmcc02** [comment]
Today I researched about Text Pre-processing.
In the coming days I will learn how to implement this using the SciKit Library.

**Comment by Cillian123** [comment]
Implemented basic chatbot using scikit tokenisation features and string cosine comparisons. I will now be working on exploring other scikit features and improving this prototype.

**Comment by brendanmcc02** [comment]
I am currently working on a function that pre-processes text (lower case, remove punctuation, tokenize, remove stopwords, lemmatize).

Currently what is blocking my progress is trying to get the lemmatize function to work

**Comment by brendanmcc02** [comment]
Finished text pre-processing. There's still a bug where if you input "You're" for example, it'll remove the ' and concatenate it into "Youre", which isn't a word recognised by the dictionary.

**Comment by Cillian123** [comment]
Changed bot to read Acts.json file and returns relevant act title and description
